### ISSUE TITLE
Продолжить

### ISSUE THREAD

**Issue by Butonix** [ADamCarraway/DTF-clone#1]
Приветствую. Не хотите продолжить за деньги?

**Comment by ADamCarraway** [comment]
> Приветствую. Не хотите продолжить за деньги?

Здравствуйте! Заманчивое предложение но не уверен что хватит знаний сделать качественную копию, да и времени на это уйдет прилично.

**Comment by Butonix** [comment]
> > Приветствую. Не хотите продолжить за деньги?
> 
> Здравствуйте! Заманчивое предложение но не уверен что хватит знаний сделать качественную копию, да и времени на это уйдет прилично.

Ну я так понял, что вы хотели себе тоже, что-то подобное. Поэтому могу простимулировать финансами. Время не торопит.

**Comment by ADamCarraway** [comment]
Да, вы правы. Мне очень нравится как выглядит и функционирует dtf. Так совпало, что я начал изучать vue.js и поэтому решил сделать копию dtf для себя, в качестве обучения, но сейчас все время уходит на работу и на это проект не хватает времени.

**Comment by ADamCarraway** [comment]
> > > Приветствую. Не хотите продолжить за деньги?
> > 
> > 
> > Здравствуйте! Заманчивое предложение но не уверен что хватит знаний сделать качественную копию, да и времени на это уйдет прилично.
> 
> Ну я так понял, что вы хотели себе тоже, что-то подобное. Поэтому могу простимулировать финансами. Время не торопит.

Было бы здорово снова начать реализовывать данный проект, да ещё и получать за это деньги

**Comment by Butonix** [comment]
> > > > Приветствую. Не хотите продолжить за деньги?
> > > 
> > > 
> > > Здравствуйте! Заманчивое предложение но не уверен что хватит знаний сделать качественную копию, да и времени на это уйдет прилично.
> > 
> > 
> > Ну я так понял, что вы хотели себе тоже, что-то подобное. Поэтому могу простимулировать финансами. Время не торопит.
> 
> Было бы здорово снова начать реализовывать данный проект, да ещё и получать за это деньги

Начинайте.) по поводу качества тут уже дело практики. Главное чтобы он уже начал стабильно функционировать, а как он функционирует это уже второй вопрос. Потом можно всегда доработать.

**Comment by Butonix** [comment]
> > > > Приветствую. Не хотите продолжить за деньги?
> > > 
> > > 
> > > Здравствуйте! Заманчивое предложение но не уверен что хватит знаний сделать качественную копию, да и времени на это уйдет прилично.
> > 
> > 
> > Ну я так понял, что вы хотели себе тоже, что-то подобное. Поэтому могу простимулировать финансами. Время не торопит.
> 
> Было бы здорово снова начать реализовывать данный проект, да ещё и получать за это деньги

Посмотрите тут
https://github.com/solvoteam/enudre демо http://erdune.com/
и тут https://github.com/AushevIbra/YJournal
Первое очень хорошо сделано, там можно вырезать многое для вашего проекта. Ребята тоже видимо тж копируют. Кстати в двух репо уже работает вебсокет уведомления лайки и тд

**Comment by ADamCarraway** [comment]
@Butonix к сожалению оба варианта не подходят. Первый немного похож на tj, а второй это вообще какой=то ужас... и в обоих случаях не используется vue поэтому придется делать все самому

**Comment by Butonix** [comment]
> @Butonix к сожалению оба варианта не подходят. Первый немного похож на tj, а второй это вообще какой=то ужас... и в обоих случаях не используется vue поэтому придется делать все самому

@ADamCarraway  тут вью используют https://github.com/voten-co/voten

**Comment by ADamCarraway** [comment]
@Butonix хорошо, я посмотрю, но не думаю что буду что-то использовать, т.к хочу сам с нуля написать
