### ISSUE TITLE
Конфликт зависимостей c последней версией php

### ISSUE THREAD

**Issue by Butonix** [ADamCarraway/DTF-clone#1]
`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires php ^7.4 but your php version (8.1.1) does not satisfy that requirement.
  Problem 2
    - Root composer.json requires pusher/pusher-php-server 4.1.1 -> satisfiable by pusher/pusher-php-server[v4.1.1].
    - pusher/pusher-php-server v4.1.1 requires php ^7.1 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 3
    - Root composer.json requires socialiteproviders/facebook ^1.0 -> satisfiable by socialiteproviders/facebook[v1.0].
    - socialiteproviders/facebook v1.0 requires php ^5.6 || ^7.0 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 4
    - Root composer.json requires socialiteproviders/google ^3.1 -> satisfiable by socialiteproviders/google[v3.1.0].
    - socialiteproviders/google v3.1.0 requires php ^5.6 || ^7.0 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 5
    - Root composer.json requires staudenmeir/eloquent-has-many-deep v1.12 -> satisfiable by staudenmeir/eloquent-has-many-deep[v1.12].
    - staudenmeir/eloquent-has-many-deep v1.12 requires php ^7.2.5 -> your php version (8.1.1) does not satisfy that requirement.
  Problem 6
    - pusher/pusher-php-server v4.1.1 requires php ^7.1 -> your php version (8.1.1) does not satisfy that requirement.
    - beyondcode/laravel-websockets[1.12.0, ..., 1.x-dev] require pusher/pusher-php-server ^3.0|^4.0|^5.0 -> satisfiable by pusher/pusher-php-server[v4.1.1].
    - Root composer.json requires beyondcode/laravel-websockets ^1.12 -> satisfiable by beyondcode/laravel-websockets[1.12.0, 1.x-dev].`

**Comment by ADamCarraway** [comment]
Я пока не обновлял php до 8 версии. Если вам очень нужно то могу обновить)
