### ISSUE TITLE
Админка

### ISSUE THREAD

**Issue by updev-digital** [ADamCarraway/DTF-clone#2]
Будет ли панель для админа и для модераторов?

**Comment by ADamCarraway** [comment]
> Будет ли панель для админа и для модераторов?

Да. Будет одна админка с разделение на роли. После теста, оптимизации запросов и фикса текущих багов, перейду к реализации админ панели.

**Comment by updev-digital** [comment]
> > Будет ли панель для админа и для модераторов?
> 
> Да. Будет одна админка с разделение на роли. После теста, оптимизации запросов и фикса текущих багов, перейду к реализации админ панели.

Когда примерно по времени планируется реализация админ панели?

**Comment by ADamCarraway** [comment]
> > > Будет ли панель для админа и для модераторов?
> > 
> > 
> > Да. Будет одна админка с разделение на роли. После теста, оптимизации запросов и фикса текущих багов, перейду к реализации админ панели.
> 
> Когда примерно по времени планируется реализация админ панели?

Не могу точно сказать, потому-что занимаюсь этим проектом в свободное время
